### ISSUE TITLE
Socket.io Polling not working :-(

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hapi-socketio-redis-chat-example#69]
https://hapi-chat.herokuapp.com/
<img width="474" alt="socket-io-polling-not-working" src="https://cloud.githubusercontent.com/assets/194400/15652784/8a216376-2680-11e6-8c11-472923b5c4d8.png">

sad panda ... 🐼 😢

**Comment by Shivang44** [comment]
Well... this is my fault I guess haha. It turns out the new socket.io js client file we included doesn't "work". Not sure why that is.

If we include the original file, 

https://cdn.socket.io/socket.io-1.3.5.js

It works. The issue we were having was that link was broken, but today, it seems the link has fixed itself. So if we didn't change anything and just waited a day it would have fixed itself haha. Anyways, I'msorry about this, I can either create a new branch with the original link or we could revert to the commit before the merge?

Thanks and sorry again for the troubles.

**Comment by nelsonic** [comment]
@Shivang44 cool. let's go back to the previous version. do you have time to PR? 👍

**Comment by Shivang44** [comment]
@nelsonic Done. It might have had to do with the version differences (1.3.5 vs 1.4.6).

**Comment by nelsonic** [comment]
@Shivang44 thanks for helping to debug this. 
the older version of Socket.io has been deployed to the app: view-source:https://hapi-chat.herokuapp.com/ but the issue is still there. sad times. 😞

**Comment by Shivang44** [comment]
@nelsonic That's really strange. I stopped my server, pulled in the latest repo, and just ran it as-is. Works for me. I'll take a deeper look at later today, but I think you and your team know _much_ more about nodejs and websockets than me :)

**Comment by Shivang44** [comment]
@nelsonic Is this resolved? It seems to work on the link you posted.

**Comment by nelsonic** [comment]
@Shivang44 yes, it appears to be working as expected.
![hapi-socketio-redis-chat-example-working](https://cloud.githubusercontent.com/assets/194400/15703413/05a2198e-27dd-11e6-98b8-192ea94cb0e6.png)

> No console errors. ✅ 

Thanks again! 👍
